name: payflow_agent
description: SyncPay BD SMS Telephony Forwarder Agent for bKash, Nagad, Rocket, Upay & Banks.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  crypto: ^3.0.3

  # Biometric Lock
  local_auth: ^2.3.0

  # Sound alert for big payments
  audioplayers: ^6.1.0

  # Export CSV / Share log
  share_plus: ^10.0.0
  path_provider: ^2.1.4

  # Local push notifications
  flutter_local_notifications: ^18.0.0

  # Charts for daily/weekly stats
  fl_chart: ^0.70.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
